### ISSUE TITLE
Add ReclaimPolicy to StorageClass

### ISSUE THREAD

**Issue by 0snug0** [rimusz/charts#10]
Feature Request

Add a configuration for ReclaimPolicy in your StorageClass template, something like

`storageClass.reclaimPolicy: Retain`

Options: are `Retain` and `Delete`

**Comment by rimusz** [comment]
hi, which chart are you talking about?

**Comment by 0snug0** [comment]
Ohh nfs provisioner

**Comment by rimusz** [comment]
released
