### ISSUE TITLE
[gcloud-sqlproxy] add support for PRIVATE IPs

### ISSUE THREAD

**Issue by rh-voice** [rimusz/charts#122]
**FEATURE REQUEST:**
add support for PRIAVTE IPs

**Which chart:**
gcloud-sqlproxy

What happened:
I needed the connect to the CloudSQL via private IP; so I modified the command for the container to:
```
/cloud_sql_proxy                                                                                                                                                                     
       --dir=/cloudsql                                                                                                                                                                      
       -instances= XXXXXXX,
       -ip_address_types=PRIVATE
```
But it would be nice to get this from the values file

**Comment by kipit** [comment]
You may use [`extraArgs`](https://github.com/rimusz/charts/blob/ebae99ba97c1e43991f339c3e63720da16e699c7/stable/gcloud-sqlproxy/templates/deployment.yaml#L70-L72) to solve your issue:

```yaml
extraArgs:
  ip_address_types: PRIVATE
```

**Comment by rh-voice** [comment]
SOLVED; thanks @kipit

**Comment by makarov-roman** [comment]
also works with
```yml
extraFlags:
  - private-ip
 ```
