### ISSUE TITLE
gcloud-sqlproxy - Helm Chart hpa fails using autoscaling/v2

### ISSUE THREAD

**Issue by ChristianGeie** [rimusz/charts#134]
Hello, in version `0.24.0` helmchart fails while applying hpa. For version `0.23.0` everything works well.

I see that between both version some changes regarding `apiVersion` happend, it was changed from `autoscaling/v2beta1`
to `autoscaling/v2` which is fine, because v2beta1 is deprecated in 1.19 and no longer served as of 1.25.

`autoscaling/v2` is available since 1.23, but has some breaking changes that are currently not reflected in the gcloud-sqlproxy chart.

I would like to suggest using `autoscaling/v2beta2` to apply HorizontalPodAutoscaler ressource.

K8s: v1.23.14-gke.1800
Error while applying helm chart:
```
Helm upgrade failed: error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targe
tAverageUtilization" in io.k8s.api.autoscaling.v2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s
.api.autoscaling.v2.ResourceMetricSource]
```

**Comment by tomrk-esteam8** [comment]
Hi, if I understand it correctly, there is an error in the way metrics are builded. 

I mean: https://github.com/rimusz/charts/blame/master/stable/gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml#L19-L29

`    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}`

when it should be sth like this: 

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-resource-metrics

`type: Resource
resource:
  name: cpu
  target:
    type: Utilization
    averageUtilization: 60`

I can try to fix it.

**Comment by rimusz** [comment]
@tomrk-esteam8 yes please :)

**Comment by tomrk-esteam8** [comment]
@ChristianGeie I would stick with 'autoscaling/v2', as it is already switched and chart is unusable anyway at this point.

**Comment by ChristianGeie** [comment]
@tomrk-esteam8 :+1:
