### ISSUE TITLE
gcloud-sqlproxy - HPA kind 

### ISSUE THREAD

**Issue by tasnyc** [rimusz/charts#142]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

If this is a BUG REPORT, please:
  - HorizontalPodAutoscaler is hardcoded as kind: Deployment .
 https://github.com/rimusz/charts/blob/36e752872a8296b39a32f87dbe626fcebc3cd2f6/stable/gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml#L14
 Would have assumed that if this is set to true 
 https://github.com/rimusz/charts/blob/36e752872a8296b39a32f87dbe626fcebc3cd2f6/stable/gcloud-sqlproxy/values.yaml#L21
 Then HorizontalPodAutoscaler  should be set to kind StatefulSet
 
**Version of Helm and Kubernetes**:
helm: 3.13.0
kubernetes: 1.24

**Which chart**:
gcloud-sqlproxy:0.25.2

**What happened**:
Template is setting my HPA kind as Deployment even though in my values.yaml file i have useStatefulset: true. 

**What you expected to happen**:
Should set the HPA kind as Statefulset instead of Deployment

*** Possible Fix***:
Probably just need an if else statement depending on what useStatefulset is set to in the values.yaml file.

Thank you

**Comment by tasnyccbs** [comment]
gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml

```
  {{- if .Values.useStatefulset }}
    kind: Statefulset
  {{- else }}
    kind: Deployment
  {{- end }}
```

**Comment by tasnyc** [comment]
gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml

```
  {{- if .Values.useStatefulset }}
    kind: Statefulset
  {{- else }}
    kind: Deployment
  {{- end }}
```
