### ISSUE TITLE
Newest version doesn't work 0.25.3

### ISSUE THREAD

**Issue by rhummelmose** [rimusz/charts#145]
Service name no longer corresponds to application name rendering the Helm chart non-functional. It caused 2 of my production setups a few hours of down time.

Please don't do something like this again.............

Caused by commit https://github.com/rimusz/charts/commit/867f85b9f5fa9d5dd13483e3308d21788c370d8f

**Comment by rhummelmose** [comment]
@danyworks @daibrahi

**Comment by rhummelmose** [comment]
This is how the problem looks when encountered:

```
➜ kubectl port-forward -n frihedsbrevet-system service/gcloud-sqlproxy :3306   
error: Pod 'gcloud-sqlproxy-6f8787bf8b-5nxjc' does not have a named port 'frihe-ems4pbefh'
```

**Comment by rhummelmose** [comment]
@rimusz

**Comment by danyworks** [comment]
@rhummelmose sorry for the inconvenience, i will fix it straight away!

**Comment by rhummelmose** [comment]
Awesome. The reason you didn't encounter this problem is because you specify the short instance name explicitly in values?
