### ISSUE TITLE
CloudSQL Memory/CPU limit causes spikes in query times

### ISSUE THREAD

**Issue by intellix** [rimusz/charts#21]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** Bug report

**Which chart**: gcloud-sqlproxy

**What happened**: CPU limit causes odd queries to spike in response time

**How to reproduce it** (as minimally and precisely as possible):
```sql
\timing
SELECT "id" FROM "User" WHERE "id" = 1;
```

Will result in response times like:
2ms, 2ms, 2ms, 50ms, 2ms, 2ms, 90ms, 2ms, 2ms

After ripping my hair out wondering how some of my API calls are slow I found this issue which mentions removing the CPU Limit stops spikes: https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/168#issuecomment-394099416

Tried it and as expected, now my queries are consistently around 2ms

So I guess what I propose is increasing the CPU limit or removing it entirely as it'll affect people using the provided one by default

**Comment by rimusz** [comment]
interesting issue, I’m going to comment out resources request and limit, so user can specify it by itself

**Comment by rimusz** [comment]
Resources got commented out in chart `v0.6.3`, it is left up to user to set them up now.

**Comment by monotek** [comment]
might be related too: kubernetes/kubernetes#67577

looking at the kernel version in the cos image the available fix should have been backported...
