### ISSUE TITLE
[stable/contour] Why use a value for namespace rather than `helm –namespace`?

### ISSUE THREAD

**Issue by philoserf** [rimusz/charts#26]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

I consider this a BUG as it is contrary to community practice.

**Version of Helm and Kubernetes**:

any supported versions

**Which chart**:

stable/contour

**What happened**:

must override a `values.yml` file default to change namespace

**What you expected to happen**:

`helm --namespace my-namespace rimusz/contour --everything else`

**Comment by rimusz** [comment]
fixed in #27
