### ISSUE TITLE
gcloud-sqlproxy installation instructions do not work with some versions of `base64`

### ISSUE THREAD

**Issue by EmperorArthur** [rimusz/charts#39]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**:
helm:
> Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

kubectl:
> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Using minikube version: v0.32.0

**Which chart**:
gcloud-sqlproxy

**What happened**:
```console
$ helm upgrade pg-sqlproxy rimusz/gcloud-sqlproxy --namespace sqlproxy \
    --set serviceAccountKey="$(cat service-account.json | base64)" \
    --set cloudsql.instances[0].instance=INSTANCE \
    --set cloudsql.instances[0].project=PROJECT \
    --set cloudsql.instances[0].region=REGION \
    --set cloudsql.instances[0].port=5432 -i
```
Does not work
Error was: 
```
Error: YAML parse error on gcloud-sqlproxy/templates/secrets.yaml: error converting YAML to JSON: yaml: line 14: could not find expected ':'
```

This was caused by the `base64` command appending newlines after so many characters.

**What you expected to happen**:
The chart to deploy properly

**How to reproduce it** (as minimally and precisely as possible):
Attempt to deploy the chart using a version of base64 that appends newlines.

**Anything else we need to know**:

The fix is to do $(cat db-proxy_key.json | base64 | tr -d '\n')`.  This removes the newlines.

Standard `set +x` was really useful for figuring this one out.

Edit:
Command is `tr -d '\n'`.  I accidentally pasted an early attempt.

**Comment by unguiculus** [comment]
`base64 --wrap=0` should work.

```console
$ helm upgrade pg-sqlproxy rimusz/gcloud-sqlproxy --namespace sqlproxy \
    --set serviceAccountKey="$(base64 --wrap=0 < service-account.json)" \
    --set cloudsql.instances[0].instance=INSTANCE \
    --set cloudsql.instances[0].project=PROJECT \
    --set cloudsql.instances[0].region=REGION \
    --set cloudsql.instances[0].port=5432 -i
```

**Comment by rimusz** [comment]
yes, going to update the chart readme. thanks for pointing it out

**Comment by rimusz** [comment]
`base64 --wrap=0` doesn't work on mac, so that's a good example for linux

**Comment by rimusz** [comment]
for multi OS is better: `$(cat service-account.json | base64 tr -d '\n')`

**Comment by naseemkullah** [comment]
Running mac but getting:

$ cat service-account.json | base64 tr -d '\n'
base64: invalid option -- d
Usage:  base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
Trying with --decode, getting:

$ cat service-account.json | base64 tr --decode '\n'
Unable to open 'tr': No such file or directory
Any other multi-OS solution for README ?

**Comment by rimusz** [comment]
sorry my bad, forgot to put the `|` in to the example: `$(cat service-account.json | base64 | tr -d '\n')`

**Comment by rimusz** [comment]
#38 fixes this issue
