### ISSUE TITLE
Allow to set reclaimPolicy in storage class

### ISSUE THREAD

**Issue by micw** [rimusz/charts#76]
**Is this a request for help?**:

No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

feature request

**Version of Helm and Kubernetes**:

does not apply

**Which chart**:

hostpath-provisioner

**What happened**:
All PVs have retain policy "delete"

**What you expected to happen**:
Retain policy should be possible to set

**How to reproduce it** (as minimally and precisely as possible):
just create a PVC, check PV's retain policy

**Anything else we need to know**:
This can easily be achieved by setting the policy for the created storage class: https://medium.com/faun/kubernetes-how-to-set-reclaimpolicy-for-persistentvolumeclaim-7eb7d002bb2e

**Comment by rimusz** [comment]
mind to do the PR?
