### ISSUE TITLE
[gcloud-sqlproxy] livenessprobe failure threshold should be higher as readinessprobe 

### ISSUE THREAD

**Issue by monotek** [rimusz/charts#78]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
3 / 1.14

**Which chart**:
glcoud-sqlproxy

**What happened**:
Best practice is that livenessprobe failure threshold should be higher as readinessprobe failure threshold to prevent unwanted restarts.

See: https://github.com/rimusz/charts/blob/master/stable/gcloud-sqlproxy/values.yaml#L108

But maybe a real readiness check via sql statement would be much nicer anyway. Would you consider to add another gcloud docker image which contains a mysql client too?

**Comment by rimusz** [comment]
mind to the PR the livenessprobe failure threshold?
Optional sidecar image with the mysql client sounds fine as well.

**Comment by monotek** [comment]
OK, i'll add an pr later this week...

**Comment by monotek** [comment]
fixed by: https://github.com/rimusz/charts/pull/82
