### ISSUE TITLE
submit to helm/charts?

### ISSUE THREAD

**Issue by gmorse81** [rimusz/charts#9]
Have you considered submitting this to helm/charts?

**Comment by rimusz** [comment]
which chart you are talking about?

**Comment by gmorse81** [comment]
charts/tree/master/stable/nfs-client-provisioner

**Comment by rimusz** [comment]
there is a PR somebody else did a while ago, I created this one as I needed a working chart, but I might submit it to `helm/charts`

**Comment by rimusz** [comment]
there is the chart already in `helm/charts/stable` so closing this issue
